<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Админка EdvardCode</title>
  <script src="https://unpkg.com/decap-cms@latest/dist/decap-cms.js"></script>
</head>
<body>
  <script>
    CMS.init();
  </script>
</body>
</html>
